# Generated by Django 2.1.2 on 2018-12-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('rating', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('comments', models.IntegerField(default=0)),
                ('excerpt', models.TextField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
