# Generated by Django 2.1.2 on 2018-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_src',
            field=models.URLField(blank=True, default=''),
        ),
    ]
