# Generated by Django 2.1.2 on 2018-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_post_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
